# Generated by Django 4.1.7 on 2023-04-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaiha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha',
            old_name='firstname',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='iha',
            name='lastname',
        ),
    ]
