# Generated by Django 4.1.7 on 2023-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaiha', '0002_rename_firstname_iha_brand_remove_iha_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
