# Generated by Django 4.1.7 on 2023-04-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaiha', '0002_remove_model_model_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
