# Generated by Django 4.1.7 on 2023-04-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentaiha', '0006_brand_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iha',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaiha.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaiha.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaiha.model', verbose_name='Model'),
        ),
    ]
