# Generated by Django 4.1.7 on 2023-04-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaiha', '0008_rename_brand_name_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
